## Classification with **Decision Tree**
by: nateghiiman@gmail.com

**Machine Learning With Python** Course 2nd Project

In [23]:
import pandas as pd

In [24]:
df=pd.read_csv("C:/python/Jadi_ML/01 Iman/3-1 heart.csv" ,index_col=False)
x=df[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh','exng', 'oldpeak', 'slp', 'caa', 'thall']].values
y=df['output'].values
df

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

Train/Test Split

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Model Training

In [26]:
from sklearn.tree import DecisionTreeClassifier
htree=DecisionTreeClassifier(criterion="entropy")
htree.fit(x_train,y_train)

yhat=htree.predict(x_test)

Evaluation

In [27]:
from sklearn import metrics
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(yhat, y_test))

DecisionTrees's Accuracy:  0.7213114754098361

In [33]:
print(metrics.classification_report(yhat,y_test))
print(metrics.confusion_matrix(yhat,y_test))

              precision    recall  f1-score   support

           0       0.73      0.71      0.72        31
           1       0.71      0.73      0.72        30

    accuracy                           0.72        61
   macro avg       0.72      0.72      0.72        61
weighted avg       0.72      0.72      0.72        61

[[22  9]
 [ 8 22]]